-- MySQL Script generated by MySQL Workbench
-- Mon Dec 21 15:18:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kowalczykw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kowalczykw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kowalczykw` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `kowalczykw` ;

-- -----------------------------------------------------
-- Table `kowalczykw`.`projekt_klient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kowalczykw`.`projekt_klient` (
  `id_klient` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NULL DEFAULT NULL,
  `nazwisko` VARCHAR(45) NULL DEFAULT NULL,
  `adres` VARCHAR(45) NULL DEFAULT NULL,
  `telefon` VARCHAR(9) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_klient`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kowalczykw`.`projekt_producent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kowalczykw`.`projekt_producent` (
  `id_producent` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(45) NULL DEFAULT NULL,
  `telefon` VARCHAR(9) NULL DEFAULT NULL,
  `adres` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_producent`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kowalczykw`.`projekt_podzespol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kowalczykw`.`projekt_podzespol` (
  `id_podzespol` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(45) NULL DEFAULT NULL,
  `producent_id` INT NULL DEFAULT NULL,
  `cena` INT NULL DEFAULT NULL,
  `opis` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_podzespol`),
  INDEX `producent_id_idx` (`producent_id` ASC) VISIBLE,
  CONSTRAINT `producent_id`
    FOREIGN KEY (`producent_id`)
    REFERENCES `kowalczykw`.`projekt_producent` (`id_producent`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kowalczykw`.`projekt_pracownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kowalczykw`.`projekt_pracownik` (
  `id_pracownik` INT NOT NULL AUTO_INCREMENT,
  `stanowisko` VARCHAR(45) NULL DEFAULT NULL,
  `imie` VARCHAR(45) NULL DEFAULT NULL,
  `nazwisko` VARCHAR(45) NULL DEFAULT NULL,
  `adres` VARCHAR(45) NULL DEFAULT NULL,
  `telefon` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `wyplata` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pracownik`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kowalczykw`.`projekt_usluga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kowalczykw`.`projekt_usluga` (
  `id_usluga` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(45) NULL DEFAULT NULL,
  `cena[zl]` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_usluga`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kowalczykw`.`projekt_zgloszenie_serwisowe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kowalczykw`.`projekt_zgloszenie_serwisowe` (
  `id_przyjecia` INT NOT NULL AUTO_INCREMENT,
  `klient_id` INT NOT NULL,
  `pracownik_id` INT NOT NULL,
  `data` DATE NULL DEFAULT NULL,
  `opis` VARCHAR(100) NULL DEFAULT NULL,
  `usluga_id` INT NOT NULL,
  `uzyty_podzespol` INT NULL DEFAULT NULL,
  `koszt` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_przyjecia`),
  INDEX `pracownik_id_idx` (`pracownik_id` ASC) VISIBLE,
  INDEX `klient_id_idx` (`klient_id` ASC) VISIBLE,
  INDEX `usluga_id_idx` (`usluga_id` ASC) VISIBLE,
  CONSTRAINT `klient_id`
    FOREIGN KEY (`klient_id`)
    REFERENCES `kowalczykw`.`projekt_klient` (`id_klient`),
  CONSTRAINT `pracownik_id`
    FOREIGN KEY (`pracownik_id`)
    REFERENCES `kowalczykw`.`projekt_pracownik` (`id_pracownik`),
  CONSTRAINT `usluga_id`
    FOREIGN KEY (`usluga_id`)
    REFERENCES `kowalczykw`.`projekt_usluga` (`id_usluga`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kowalczykw`.`projekt_reklamacja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kowalczykw`.`projekt_reklamacja` (
  `id_reklamacja` INT NOT NULL AUTO_INCREMENT,
  `serwis_id` INT NULL DEFAULT NULL,
  `data_zgloszenia` DATE NULL DEFAULT NULL,
  `klient_id` INT NULL DEFAULT NULL,
  `opis` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_reklamacja`),
  INDEX `serwis_id_idx` (`serwis_id` ASC) VISIBLE,
  CONSTRAINT `serwis_id`
    FOREIGN KEY (`serwis_id`)
    REFERENCES `kowalczykw`.`projekt_zgloszenie_serwisowe` (`id_przyjecia`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `kowalczykw` ;

-- -----------------------------------------------------
-- function liczba_klient
-- -----------------------------------------------------

DELIMITER $$
USE `kowalczykw`$$
CREATE DEFINER=`kowalczykw`@`localhost` FUNCTION `liczba_klient`() RETURNS int
BEGIN
    DECLARE liczba_klientow INT;
    SELECT COUNT(*) INTO @liczba_klientow FROM projekt_klient;
    RETURN @liczba_klientow;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure premia_dla_serwisantow
-- -----------------------------------------------------

DELIMITER $$
USE `kowalczykw`$$
CREATE DEFINER=`kowalczykw`@`localhost` PROCEDURE `premia_dla_serwisantow`(IN id int)
BEGIN
Update projekt_pracownik set wyplata = 1.1 * wyplata where id_pracownik = 1 and id_pracownik = 2;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `kowalczykw`;

DELIMITER $$
USE `kowalczykw`$$
CREATE
DEFINER=`kowalczykw`@`localhost`
TRIGGER `kowalczykw`.`projekt_klient_before_insert_email`
BEFORE INSERT ON `kowalczykw`.`projekt_klient`
FOR EACH ROW
BEGIN   
IF NEW.email = null   
THEN     
SET NEW.email = "brak adresu email";  
 END IF; 
 END$$

USE `kowalczykw`$$
CREATE
DEFINER=`kowalczykw`@`localhost`
TRIGGER `kowalczykw`.`projekt_klient_before_insert_telefon`
BEFORE INSERT ON `kowalczykw`.`projekt_klient`
FOR EACH ROW
BEGIN
  IF NEW.telefon = null
  THEN
    SET NEW.telefon = "brak numeru telefonu";
  END IF;
END$$

USE `kowalczykw`$$
CREATE
DEFINER=`kowalczykw`@`localhost`
TRIGGER `kowalczykw`.`projekt_zgloszenie_serwisowe_minimalny_koszt_uslugi`
BEFORE INSERT ON `kowalczykw`.`projekt_zgloszenie_serwisowe`
FOR EACH ROW
BEGIN
  IF NEW.koszt < 0
  THEN
    SET NEW.koszt = 30;
  END IF;
END$$


DELIMITER ;
